name: pfe_test
description: A gamified AI tutor for software engineering.
version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1
  appwrite: ^21.0.0
  image_picker: ^1.0.4
  dropdown_button2: ^2.3.9
  http: ^1.6.0
  flutter_local_notifications: ^20.1.0
  google_sign_in: ^7.2.0
  sign_in_button: ^4.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
 



flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/badges/
